import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{padding:12, borderBottom:'1px solid #eee'}}>
          <nav style={{display:'flex', gap:16}}>
            <a href="/">Accueil</a>
            <a href="/taxa">Taxons</a>
            <a href="/identify">Identifier</a>
          </nav>
        </header>
        {children}
      </body>


    </html>
  );
}
